# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndicativoCaja', models.CharField(max_length=5)),
                ('NumeroCaja', models.IntegerField()),
                ('NombreFuncionario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Tel', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoTurno', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoTurno',
                'verbose_name_plural': 'TipoTurnos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoTurno', models.CharField(max_length=1000)),
                ('Estado', models.BooleanField()),
                ('Caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnos.Caja')),
                ('TipoTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnos.TipoTurno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='TipoTurnos',
            field=models.ManyToManyField(to='Turnos.TipoTurno'),
        ),
    ]
