# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to=b'')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='tipoturno',
            options={'verbose_name': 'Tipo Turno', 'verbose_name_plural': 'Tipo Turnos'},
        ),
    ]
