# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0004_turno_horacreacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='Caja',
        ),
    ]
