# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0005_remove_turno_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('NombreFuncionario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'UsuarioCaja',
                'verbose_name_plural': 'UsuarioCajas',
            },
        ),
        migrations.RemoveField(
            model_name='caja',
            name='NombreFuncionario',
        ),
        migrations.AddField(
            model_name='usuariocaja',
            name='Caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnos.Caja'),
        ),
    ]
