# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0006_auto_20170203_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='Caja',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Turnos.Caja'),
        ),
    ]
