# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0007_turno_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='Llamados',
            field=models.IntegerField(default=3),
        ),
    ]
